import {
  faWifi,
  faBathtub,
  faSwimmingPool,
  faToiletPaper,
  faTelevision,
  faShower,
  faCoffee,
  faBicycle,
  faFan,
  faMobilePhone,
  faSnowflake,
  faBed,
  faBus,
  faTable,
  faChair,
  faSmoking,
  faSmokingBan,
  faHotTub,
  faGlassMartiniAlt,
  faUtensils,
  faDog
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  "faWifi": faWifi,
  "faBathtub": faBathtub,
  "faSwimmingPool": faSwimmingPool,
  "faToiletPaper": faToiletPaper,
  "faTelevision": faTelevision,
  "faShower": faShower,
  "faCoffee": faCoffee,
  "faBicycle": faBicycle,
  "faFan": faFan,
  "faMobilePhone": faMobilePhone,
  "faSnowflake": faSnowflake,
  "faBed": faBed,
  "faBus": faBus,
  "faTable": faTable,
  "faChair": faChair,
  "FaSmokingBan": faSmokingBan,
  "FaSmoking": faSmoking,
  "FaHotTub": faHotTub,
  "FaGlassMartinAlt": faGlassMartiniAlt,
  "FaUtensils": faUtensils,
  "FaDog": faDog
};
